name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      clean_build:
        description: "Remove Buildozer cache"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/kivy/buildozer:master

    steps:
      - uses: actions/checkout@v5

      - name: Clean cache
        if: ${{ inputs.clean_build }}
        run: |
          rm -rf ~/.buildozer
          rm -rf .buildozer
          rm -rf bin

      - name: Restore Buildozer cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Create database
        run: |
          python -m database.init_db

      - name: Check Python
        run: |
          python --version
          pip --version

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: spirit-island-debug
          path: bin/*.apk